### ISSUE TITLE
Log label is not surrounded by spaces

### ISSUE THREAD

**Issue by sudomoose** [PassTheMayo/mayo-logs#1]
Evidence:
**what it shouldn't be (but what it is):**
https://is-a-shit.host/ejn47z1v.png

**what is should be (but isn't):**
https://ytdl.finally-fucking.works/YNseN6Dt.png

pls fix kthnx

**Comment by PassTheMayo** [comment]
Can you provide your code for addMethod?

**Comment by sudomoose** [comment]
I'm using defaults

**Comment by sudomoose** [comment]
> Can you provide your code for addMethod or are you using defaults?

defaults

**Comment by PassTheMayo** [comment]
This has been fixed in 1.0.3.

**Comment by sudomoose** [comment]
Awesome :)
